### ISSUE TITLE
GPU under utilization due to low occupancy.

### ISSUE THREAD

**Issue by jiay7** [titu1994/warprnnt_numba#3]
Thank you for the warprnnt_numba, I got the warnning (show blow) when I use this loss in my code.
![1650880807(1)](https://user-images.githubusercontent.com/74249633/165067175-422420db-ccca-4b23-a1de-2bf2a1209fa1.png)
Is this known issue? How can it be debugged and solved?

Thank you!

**Comment by titu1994** [comment]
Yes this is a Numba level logging showing that the gpu is being underutilized (low occupancy). This is perfectly fine, since the kernels alpha beta kernels are designed to run at the batch size (and memory is a premium when training RNNTs). 

If you somehow have memory, you can use batch sizes above 160 mentioned here to completely utilize the GPU

**Comment by jiay7** [comment]
Yes, it seems that these warnings did not affect the training results. Thank you very much for your reply.
